link<-"https://d396qusza40orc.cloudfront.net/exdata%2Fdata%2Fhousehold_power_consumption.zip"
download.file(link, destfile = "./exhousehold.zip", method = "curl")
unzip(zipfile = "./exhousehold.zip")
rawdata<- read.table("./household_power_consumption.txt", sep = ";", na.strings = "?", header = TRUE, stringsAsFactors = FALSE)
library(dplyr)
cutdata<- filter(rawdata, Date == "1/2/2007"| Date == "2/2/2007")
combo_time <-paste(cutdata$Date, cutdata$Time, collapse = NULL, sep = ' ')
library(lubridate)
Date_time<-strptime(combo_time, format = "%d/%m/%Y %H:%M:%S")
cutdata1<-select(cutdata, Global_active_power : Sub_metering_3)
dataready<- cbind(Date_time, cutdata1)
dataready<- mutate(dataready, weekday=wday(Date_time, label = TRUE, abbr = TRUE))
## Fun with data subsets
par(mar = c(2, 4, 1, 1))
with(dataready, plot(Date_time, Sub_metering_1, type = "n", main = "", ylab = "Engery sub metering", xlab = ""))
lines(dataready$Date_time, dataready$Sub_metering_1, col = "black")
lines(dataready$Date_time, dataready$Sub_metering_2, col = "red")
lines(dataready$Date_time, dataready$Sub_metering_3, col = "blue")
legend("topright", lwd = 1, bg = "transparent", col = c("black", "red", "blue"), legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
## Print to PNG and turn device off
dev.copy(png, file = "plot3.png")
dev.off()